map_type: costmap

obstacle_range: 6.00
raytrace_range: 5.00
min_obstacle_height: 1.0



transform_tolerance: 0.2

#<box size=".8128 .508 .508"/> plus wheel width and link offset to 0.3564 and extension of caster to the rear
footprint: [[0.42, 0.36], [-0.48, 0.36], [-0.48, -0.36], [0.42, -0.36]]
inflation_radius: 0.3


observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /custom_bot/laser/scan, marking: true, clearing: true}
