TrajectoryPlannerROS:

  holonomic_robot: false

  max_vel_x: 0.8
  min_vel_x: 0.2

  # max_vel_theta: 1.0
  # min_in_place_vel_theta: 0.4

  # acc_lim_theta: 3.2
  # acc_lim_x: 2.5
  # acc_lim_y: 2.5

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.15
  sim_time: 3.0
  meter_scoring: true
  pdist_scale: 1.5 #default 0.6 weight to follow path
  gdist_scale:  1.0 #default 0.8 weight to reach local goal
  publish_cost_grid_pc: true
  heading_scoring: false #default false
  heading_lookahead: 2.0
  occdist_scale: 0.01

