TrajectoryPlannerROS:

  holonomic_robot: false

  max_vel_x: 0.5 #default 0.5
  min_vel_x: 0.1 #default 0.1

  # max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4 #default 0.4

  # acc_lim_theta: 3.2
  # acc_lim_x: 2.5
  # acc_lim_y: 2.5

  yaw_goal_tolerance: 0.05 #default 0.05
  xy_goal_tolerance: 0.1 #default 0.1
  
  sim_time: 3.0
  meter_scoring: true
  pdist_scale: 0.7 #default 0.6 weight to follow path
  gdist_scale:  0.8 #default 0.8 weight to reach local goal
  publish_cost_grid_pc: true
  heading_scoring: false #default false
  heading_lookahead: 0.50
  occdist_scale: 0.1

