map_type: costmap

obstacle_range: 5.00
raytrace_range: 4.50
min_obstacle_height: 0.0

transform_tolerance: 0.5

#<box size=".4 .2 .1"/>
footprint: [[0.2, 0.1], [-0.2, 0.1], [-0.2, -0.1], [0.2, -0.1]]
inflation_radius: 0.5


observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
